name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run flake8 (optional)
        run: python -m pip install flake8 || true
      - name: Run basic smoke test
        run: python -c "import pandas as pd; print('smoke test ok')"
